/*
 * platform_manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MetasphereStatus {
    #[serde(rename = "InProgress")]
    InProgress,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "Deleted")]
    Deleted,
    #[serde(rename = "Failed")]
    Failed,

}

impl std::fmt::Display for MetasphereStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InProgress => write!(f, "InProgress"),
            Self::Completed => write!(f, "Completed"),
            Self::Deleted => write!(f, "Deleted"),
            Self::Failed => write!(f, "Failed"),
        }
    }
}

impl Default for MetasphereStatus {
    fn default() -> MetasphereStatus {
        Self::InProgress
    }
}

