/*
 * platform_manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProjectRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: i32,
}

impl CreateProjectRequest {
    pub fn new(name: String, tenant_id: i32) -> CreateProjectRequest {
        CreateProjectRequest {
            name,
            tenant_id,
        }
    }
}

