/*
 * platform_manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserRequest {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(rename = "last_name")]
    pub last_name: String,
    #[serde(rename = "role")]
    pub role: models::Roles,
    #[serde(rename = "tenant_id")]
    pub tenant_id: i32,
}

impl CreateUserRequest {
    pub fn new(email: String, first_name: String, last_name: String, role: models::Roles, tenant_id: i32) -> CreateUserRequest {
        CreateUserRequest {
            email,
            first_name,
            last_name,
            role,
            tenant_id,
        }
    }
}

