/*
 * platform_manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMetasphereResponse {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
}

impl CreateMetasphereResponse {
    pub fn new(id: i32, uuid: uuid::Uuid) -> CreateMetasphereResponse {
        CreateMetasphereResponse {
            id,
            uuid,
        }
    }
}

