/*
 * platform_manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectInfo {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "sphere_count")]
    pub sphere_count: i32,
    #[serde(rename = "tenant_id")]
    pub tenant_id: i32,
}

impl ProjectInfo {
    pub fn new(id: i32, is_active: bool, label: String, sphere_count: i32, tenant_id: i32) -> ProjectInfo {
        ProjectInfo {
            id,
            is_active,
            label,
            sphere_count,
            tenant_id,
        }
    }
}

