/*
 * platform_manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Roles {
    #[serde(rename = "MG_ADMIN")]
    MgAdmin,
    #[serde(rename = "MG_DEVELOPER")]
    MgDeveloper,
    #[serde(rename = "None")]
    None,

}

impl std::fmt::Display for Roles {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MgAdmin => write!(f, "MG_ADMIN"),
            Self::MgDeveloper => write!(f, "MG_DEVELOPER"),
            Self::None => write!(f, "None"),
        }
    }
}

impl Default for Roles {
    fn default() -> Roles {
        Self::MgAdmin
    }
}

