/*
 * platform_manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamInfo {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: i32,
}

impl TeamInfo {
    pub fn new(id: i32, is_active: bool, name: String, tenant_id: i32) -> TeamInfo {
        TeamInfo {
            id,
            is_active,
            name,
            tenant_id,
        }
    }
}

