/*
 * platform_manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TenantInfo {
    #[serde(rename = "admin_id")]
    pub admin_id: i32,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "logo")]
    pub logo: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "website")]
    pub website: String,
}

impl TenantInfo {
    pub fn new(admin_id: i32, id: i32, is_active: bool, logo: String, name: String, slug: String, website: String) -> TenantInfo {
        TenantInfo {
            admin_id,
            id,
            is_active,
            logo,
            name,
            slug,
            website,
        }
    }
}

