/*
 * platform_manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProjectRequest {
    #[serde(rename = "new_name")]
    pub new_name: String,
}

impl UpdateProjectRequest {
    pub fn new(new_name: String) -> UpdateProjectRequest {
        UpdateProjectRequest {
            new_name,
        }
    }
}

